<?php ?>
<div id="barcodeMessage" style="display:none;"><ul class="messages"><li id="barcode-li-message" class="success-msg"><ul><li id="barcodeMessageContent"></li></ul></li></ul></div>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('rma')->__('RMA - Manage Return Products') ?></h3></td>
            <td class="a-right">
                <?php //echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="barcode-order">
    <form id="frmOrder" method="post" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/rma_ajax/save/"); ?>">
        <div class="order-left">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden"  id="save-action" name="save_action" value="" />
            <div class="order-left-id">Order barcode #:</div>
            <div class="order-left-input">
                <input type="text" id="order-id" name="order_id" class="input-text" style="text-align:center;" />
            </div>
            <div class="order-left-id">Product barcode #:</div>
            <div class="order-left-input">                
                <input type="text" id="product-id" name="order_product_id" class="input-text" onfocus="javascript:this.value='';" style="text-align:center;" />
            </div>
            <!--div class="order-left-webcam">Webcam</div-->
            <div id="barcode-view" class="order-left-barcode-view"></div>
            <div style="clear:both"></div>
        </div>
        <div class="order-right"><?php echo $this->getReturnProductsGridHtml() ?>
        </div>
    </form>
    <div style="text-align: right; width:100%; height: 40px; float: right;">
        <button id="barcode-button-return" class="scalable inactive" type="button"  onclick="ajaxSaveOrder(this,'create_rma');"><span><?php echo $this->__('Create RMA') ?></span></button>
        <button id="barcode-button-resetall" class="scalable inactive" type="button"  onclick="manualResetAll(this);"><span><?php echo $this->__('Reset All') ?></span></button>
    </div>
</div>
<script type="text/javascript">

    localStorage.removeItem('#tournament tr');
    $('order-id').focus();
    $('order-id').observe('keypress', order_keypressHandler);
    $('product-id').observe('keypress', product_keypressHandler);

    function order_keypressHandler(event){
        if(event.keyCode == 13 && $('order-id').value.length >= 3){
            rmaShowOrderProducts();
        }

        //XBAR-726 - tungdt2
        localStorage.clear();

    }

    function product_keypressHandler(event){
        if(event.keyCode == 13 && $('product-id').value.length >= 3){
            ajaxLoadBarcodeImage(-1,3
            );//action 3 = scan product by text box product's barcode

        }

    }


    function scanned(obj,act){
        //alert(act);
        //var product_id_nam = $(this).attr('pro_id');
        //alert(product_id_nam+"id la");
        ajaxLoadBarcodeImage(obj,act);
       // obj.checked = false;
    }

    function rmaShowOrderProducts(){
        var url = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/rma_ajax/checkReturnOrder') ?>';
        new Ajax.Request(url, {
            method: 'post',
            parameters: $('frmOrder').serialize(true),
            onComplete: function(transport) {
                var data = transport.responseText.evalJSON();
                if(!data.error){
                    if (!data.valid_duration || data.valid_duration=="false"){
                        openMessagePopup('The order is invalid for RMA duration!');
                    }                    
                    $('order-id').writeAttribute('readonly', 'readonly');
                    $('product-id').value = '';
                    $('barcode-view').innerHTML = '';
				
                    $('product-id').focus();
                    enableButton('barcode-button-resetall');
                }
                else{
                    $('order-id').value = '';
                    disableButton('barcode-button-return');
                    $('order-id').focus();
				
                    //show error
                    $('barcode-li-message').className = "error-msg";
                    $('barcodeMessageContent').innerHTML = data.message;
                    $('barcodeMessage').show();
                    Element.hide.delay(10, $('barcodeMessage'));
                }
                rmaReturnProductsGridJsObject.addVarToUrl('order_id', data.order_id);
                //rmaReturnProductsGridJsObject.addVarToUrl('form_key', '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>');
                if (data.order_id)
                rmaReturnProductsGridJsObject.doFilter();
            }
        });
    }

    function ajaxLoadBarcodeImage(pro_id,act){
        var reloadurl = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/rma_ajax/loadreturnbarcodeimage') ?>';
        new Ajax.Request(reloadurl, {
            method: 'post',
            parameters: $('frmOrder').serialize()+'&product_id_nam='+pro_id,
            onComplete: function(transport) {
                var data = transport.responseText.evalJSON();
                console.log(data);
                if(data.error != ''){
                    $('barcode-view').innerHTML = data.error;
                }
                else{
                    var count = data.count;
                   // console.log(count);
                    if(count==1){
                        if(act==1 || act==3){
                            $('barcode-view').innerHTML = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>barcode/'+data.image_name+'_<?php echo Mage::getStoreConfig('barcode/general/symbology');?>_bc.png?<?php echo time();?>"  alt="" style="vertical-align:middle;" />';
                            if(data.product_in_order){
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_success.gif') ?>" width="16px" height="16px" alt="OK" />';
                                var qty_returned = $('qty-returned-'+data.product_id).innerHTML*1;
                                var qty_scanned = $('qty-scanned-'+data.product_id).innerHTML*1;
                                var qty_shipped = $('qty-shipped-'+data.product_id).innerHTML*1;
                                if((qty_scanned+qty_returned) < qty_shipped){

                                    //XBAR-726 - tungdt2
                                    $('qty-scanned-'+data.product_id).innerHTML = $('qty-scanned-'+data.product_id).innerHTML*1+1;
                                    var quantity = $('qty-scanned-'+data.product_id).innerHTML;
                                    if(quantity!=0){
                                        localStorage.setItem('qty-scanned-'+data.product_id, quantity);
                                    }
                                        document.getElementById('qty-scanned-'+data.product_id).innerHTML = localStorage.getItem('qty-scanned-'+data.product_id);


                                    $('qty-scanned-hidden-'+data.product_id).value = $('qty-scanned-hidden-'+data.product_id).value*1+1;
                                    if(($('qty-scanned-'+data.product_id).innerHTML*1+$('qty-returned-'+data.product_id).innerHTML*1) == $('qty-shipped-'+data.product_id).innerHTML*1){

                                        //X-BarCode/RMAXBAR-740 tungdt
                                        var img = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                        localStorage.setItem('qty-valid-'+data.product_id, img);

                                        $('qty-valid-'+data.product_id).innerHTML = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                    }

                                    enableButton('barcode-button-return');
                                }
                                else{
                                    $('barcode-li-message').className = "error-msg";
                                    $('barcodeMessageContent').innerHTML = 'Out of Qty Shipped';
                                    $('barcodeMessage').show();

                                    Element.hide.delay(10, $('barcodeMessage'));
                                }
                            }
                            else{
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_error.gif') ?>" width="16px" height="16px" alt="ERROR" />';
                            }
                        }
                        if(act==0){
                            $('barcode-view').innerHTML = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>barcode/'+data.image_name+'_<?php echo Mage::getStoreConfig('barcode/general/symbology');?>_bc.png?<?php echo time();?>"  alt="" style="vertical-align:middle;" />';
                            if(data.product_in_order){
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_success.gif') ?>" width="16px" height="16px" alt="OK" />';
                                var qty_returned = $('qty-returned-'+data.product_id).innerHTML*1;
                                var qty_scanned = $('qty-scanned-'+data.product_id).innerHTML*1;
                                var qty_shipped = $('qty-shipped-'+data.product_id).innerHTML*1;
                                if(qty_scanned >0 ){

                                    //X-BarCode/RMAXBAR-740 tungdt
                                    $('qty-scanned-'+data.product_id).innerHTML = $('qty-scanned-'+data.product_id).innerHTML*1-1;
                                    var quantity = $('qty-scanned-'+data.product_id).innerHTML;
                                    if(quantity!=0){
                                        localStorage.setItem('qty-scanned-'+data.product_id, quantity);
                                    }
                                    document.getElementById('qty-scanned-'+data.product_id).innerHTML = localStorage.getItem('qty-scanned-'+data.product_id);


                                    $('qty-scanned-hidden-'+data.product_id).value = $('qty-scanned-hidden-'+data.product_id).value*1-1;
                                    if(($('qty-scanned-'+data.product_id).innerHTML*1+$('qty-returned-'+data.product_id).innerHTML*1) == $('qty-shipped-'+data.product_id).innerHTML*1){
                                        var img = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                        localStorage.setItem('qty-valid-'+data.product_id, img);
                                        $('qty-valid-'+data.product_id).innerHTML = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                    }
                                    else{
                                        localStorage.removeItem('qty-valid-'+data.product_id, img);
                                        $('qty-valid-'+data.product_id).innerHTML="";
                                    }

                                    enableButton('barcode-button-return');
                                }
                                else{
                                    $('barcode-li-message').className = "error-msg";
                                    $('barcodeMessageContent').innerHTML = 'Qty Scanned is 0';
                                    $('barcodeMessage').show();

                                    Element.hide.delay(10, $('barcodeMessage'));
                                }
                            }
                            else{
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_error.gif') ?>" width="16px" height="16px" alt="ERROR" />';
                            }
                        }
                        if(act==2){
                            $('barcode-view').innerHTML = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>barcode/'+data.image_name+'_<?php echo Mage::getStoreConfig('barcode/general/symbology');?>_bc.png?<?php echo time();?>"  alt="" style="vertical-align:middle;" />';
                            if(data.product_in_order){
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_success.gif') ?>" width="16px" height="16px" alt="OK" />';
                                var qty_returned = $('qty-returned-'+data.product_id).innerHTML*1;
                                var qty_scanned = $('qty-scanned-'+data.product_id).innerHTML*1;
                                var qty_shipped = $('qty-shipped-'+data.product_id).innerHTML*1;
                                var qty_ordered = $('qty-ordered-'+data.product_id).innerHTML*1;
                                if(qty_scanned+qty_returned != qty_shipped){

                                    //X-BarCode/RMAXBAR-740 tungdt
                                    $('qty-scanned-'+data.product_id).innerHTML = qty_shipped-qty_returned;
                                    var quantity = $('qty-scanned-'+data.product_id).innerHTML;
                                    if(quantity!=0){
                                        localStorage.setItem('qty-scanned-'+data.product_id, quantity);
                                    }
                                    document.getElementById('qty-scanned-'+data.product_id).innerHTML = localStorage.getItem('qty-scanned-'+data.product_id);

                                    $('qty-scanned-'+data.product_id).innerHTML = qty_shipped-qty_returned;
                                    $('qty-scanned-hidden-'+data.product_id).value = qty_shipped-qty_returned;
                                    if(($('qty-scanned-'+data.product_id).innerHTML*1+$('qty-returned-'+data.product_id).innerHTML*1) == $('qty-shipped-'+data.product_id).innerHTML*1){
                                        var img = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                        localStorage.setItem('qty-valid-'+data.product_id, img);
                                        $('qty-valid-'+data.product_id).innerHTML = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                    }
                                    else{
                                        $('qty-valid-'+data.product_id).innerHTML="";
                                    }

                                    enableButton('barcode-button-return');
                                }
                                else{
                                    $('barcode-li-message').className = "error-msg";
                                    $('barcodeMessageContent').innerHTML = 'Qty Scanned is full';
                                    $('barcodeMessage').show();

                                    Element.hide.delay(10, $('barcodeMessage'));
                                }
                            }
                            else{
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_error.gif') ?>" width="16px" height="16px" alt="ERROR" />';
                            }
                        }
                    }
                    if(count>1){
                       // console.log("nam");
                       // console.log(count);
                        if(act==1 || act==3){
                            var i=0;
                            $('barcode-view').innerHTML = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>barcode/'+data.image_name+'_<?php echo Mage::getStoreConfig('barcode/general/symbology');?>_bc.png?<?php echo time();?>"  alt="" style="vertical-align:middle;" />';
                                if(data.product_in_order){
                                    $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_success.gif') ?>" width="16px" height="16px" alt="OK" />';
                                    for(i=0;i<count;i++){

                                        var qty_returned = $$('.qty-returned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                        var qty_scanned = $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                        var qty_shipped = $$('.qty-shipped-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                        if(qty_scanned+qty_returned< qty_shipped){
                                            $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML = $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1+1;
                                            $$('.qty-scanned-hidden-'+data.product_id+':eq('+i+')')[0].value = $$('.qty-scanned-hidden-'+data.product_id+':eq('+i+')')[0].value*1+1;
                                            if($$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1 == $$('.qty-shipped-'+data.product_id+':eq('+i+')')[0].innerHTML*1){
                                                $$('.qty-valid-'+data.product_id+':eq('+i+')')[0].innerHTML = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                            }

                                            enableButton('barcode-button-return');
                                            break;
                                        }
                                        else{
                                            if(i==count-1){
                                                $('barcode-li-message').className = "error-msg";
                                                $('barcodeMessageContent').innerHTML = 'Out of Qty Shipped';
                                                $('barcodeMessage').show();
                                                Element.hide.delay(20, $('barcodeMessage'));
                                            }

                                        }
                                    }
                                }
                                else{
                                    $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_error.gif') ?>" width="16px" height="16px" alt="ERROR" />';
                                }

                        }
                        if(act==0){
                            $('barcode-view').innerHTML = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>barcode/'+data.image_name+'_<?php echo Mage::getStoreConfig('barcode/general/symbology');?>_bc.png?<?php echo time();?>"  alt="" style="vertical-align:middle;" />';
                            var i=0;
                            if(data.product_in_order){
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_success.gif') ?>" width="16px" height="16px" alt="OK" />';
                                for(i=0;i<count;i++){

                                    //var qty_returned = $$('.qty-returned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    var qty_returned = $$('.qty-returned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    var qty_scanned = $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    var qty_shipped = $$('.qty-shipped-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    if(qty_scanned >0 ){
                                        $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML = $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1-1;
                                        $$('.qty-scanned-hidden-'+data.product_id+':eq('+i+')')[0].value = $$('.qty-scanned-hidden-'+data.product_id+':eq('+i+')')[0].value*1-1;
                                        if($$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1== $$('.qty-shipped-'+data.product_id+':eq('+i+')')[0].innerHTML*1){
                                            $$('.qty-valid-'+data.product_id+':eq('+i+')')[0].innerHTML = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                        }
                                        else{
                                            $$('.qty-valid-'+data.product_id+':eq('+i+')')[0].innerHTML="";
                                        }

                                        enableButton('barcode-button-return');
                                        break;
                                    }
                                    else{
                                        if(i==count-1){
                                            $('barcode-li-message').className = "error-msg";
                                            $('barcodeMessageContent').innerHTML = 'Qty Scanned is 0';
                                            $('barcodeMessage').show();
                                            Element.hide.delay(10, $('barcodeMessage'));
                                        }
                                        else
                                            continue;
                                    }
                                }
                            }
                            else{
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_error.gif') ?>" width="16px" height="16px" alt="ERROR" />';
                            }
                        }
                        if(act==2){
                            $('barcode-view').innerHTML = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>barcode/'+data.image_name+'_<?php echo Mage::getStoreConfig('barcode/general/symbology');?>_bc.png?<?php echo time();?>"  alt="" style="vertical-align:middle;" />';
                            var i=0;
                            if(data.product_in_order){
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_success.gif') ?>" width="16px" height="16px" alt="OK" />';
                                for(i=0;i<count;i++){
                                    var qty_returned = $$('.qty-returned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    var qty_scanned = $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    var qty_shipped = $$('.qty-shipped-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    var qty_ordered = $$('.qty-ordered-'+data.product_id+':eq('+i+')')[0].innerHTML*1;
                                    if((qty_scanned+qty_returned) != qty_shipped){
                                        $$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML = qty_shipped-qty_returned;
                                        $$('.qty-scanned-hidden-'+data.product_id+':eq('+i+')')[0].value = qty_shipped-qty_returned;
                                        if(($$('.qty-scanned-'+data.product_id+':eq('+i+')')[0].innerHTML*1+$$('.qty-returned-'+data.product_id+':eq('+i+')')[0].innerHTML*1) == $$('.qty-shipped-'+data.product_id+':eq('+i+')')[0].innerHTML*1){
                                            $$('.qty-valid-'+data.product_id+':eq('+i+')')[0].innerHTML = '<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="Valid" />';
                                        }
                                        else{
                                            $$('.qty-valid-'+data.product_id+':eq('+i+')')[0].innerHTML="";
                                        }

                                        enableButton('barcode-button-return');
                                        break;
                                    }
                                    else{
                                        if(i==count-1){
                                            $('barcode-li-message').className = "error-msg";
                                            $('barcodeMessageContent').innerHTML = 'Qty Scanned is full';
                                            $('barcodeMessage').show();

                                            Element.hide.delay(10, $('barcodeMessage'));
                                        }
                                        else continue;

                                    }
                                }
                            }
                            else{
                                $('barcode-view').innerHTML += '<img src="<?php echo $this->getSkinUrl('sm/images/barcode_error.gif') ?>" width="16px" height="16px" alt="ERROR" />';
                            }
                        }
                    }



                }
            
                // reset product-id
                $('product-id').value='';
                $('product-id').focus();
            }
        });

    }

    function ajaxSaveOrder(obj, act){
        if(obj.className != "scalable task"){
            $('barcode-li-message').className = "error-msg";
            $('barcodeMessageContent').innerHTML = 'Must have qty scanned to refund!';
            $('barcodeMessage').show();
            return false;
        }
        $('save-action').value = act;
        var url = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/rma_ajax/save') ?>';
        new Ajax.Request(url, {
            method: 'post',
            parameters: $('frmOrder').serialize(true),
            onComplete: function(transport){

                var data = transport.responseText.evalJSON();
                if(data.error){

                    $('barcode-li-message').className = "error-msg";
                }
                else{
//                    $('loading_mask_loader').setStyle({display:'none'});
//                    $('loading-mask').setStyle({display:'none'});
                    $('barcode-li-message').className = "success-msg";
                    resetAll();
                }

                $('barcodeMessageContent').innerHTML = data.message;
                $('barcodeMessage').show();

                Element.hide.delay(10, $('barcodeMessage'));
            }
        });
    }

    function manualResetAll(obj){
        if(obj.className != "scalable task"){
            return false;
        }
        else{
            resetAll();
        }
    }

    function resetAll(){
        $('frmOrder').reset();
        $('order-id').writeAttribute('readonly', false);
        $('order-id').focus();
        $('barcode-view').innerHTML = '';
        resetProductsGrid();
        disableButton('barcode-button-return');
        disableButton('barcode-button-partial');
        disableButton('barcode-button-hold');
        disableButton('barcode-button-backorder');
        disableButton('barcode-button-resetall');
    }

    function disableButton(id){
        if($(id))
            $(id).className = "scalable inactive";
        return;
    }

    function enableButton(id){
        if($(id))
            $(id).className = "scalable task";
        return;
    }

    function resetProductsGrid(){
        rmaReturnProductsGridJsObject.addVarToUrl('order_id', 0);
        rmaReturnProductsGridJsObject.addVarToUrl('form_key', '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>');
        rmaReturnProductsGridJsObject.doFilter();
    }

</script>
<div id="message-popup-window-mask" style="display:none;"></div>
<div id="message-popup-window" class="message-popup">
    <div class="message-popup-head">
        <a href="#" onclick="closeMessagePopup(); return false;" title="Close"><span>Close</span></a>
        <h2>SmartOSC Barcode/RMA</h2>
    </div>
    <div class="message-popup-content">
        <div class="message">
            <span class="message-icon message-notice" style="background-image:url(http://widgets.magentocommerce.com/1.6.1.0/SEVERITY_NOTICE.gif);">notice</span>
            <p class="message-text">This order has exceeded the <strong><?php echo Mage::getStoreConfig('barcode/rma/valid_duration')?> days</strong> return period. You can still create an RMA as an admin.</p>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var messagePopupClosed = false;
    function openMessagePopup() {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height+'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
        $('message-popup-window').addClassName('show');
    }

    function closeMessagePopup() {
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Element.hide('message-popup-window-mask');
        $('message-popup-window').removeClassName('show');
        messagePopupClosed = true;
    }

//    Event.observe(window, 'keyup', function(evt) {
//        if(messagePopupClosed) return;
//        var code;
//        if (evt.keyCode) code = evt.keyCode;
//        else if (evt.which) code = evt.which;
//        if (code == Event.KEY_ESC) {
//            closeMessagePopup();
//        }
//    });
//]]>
</script>
<?php 
